import os
from typing import Sequence

import requests

QWEN_EMBED_URL = os.getenv("QWEN_EMBED_URL", "http://localhost:11434/api/embed")
QWEN_EMBED_MODEL = os.getenv("QWEN_EMBED_MODEL", "text-embedding-qwen3-embedding-0.6b")


def embed(text: str) -> Sequence[float]:
    """Return the embedding generated by the qwen embedding endpoint."""

    response = requests.post(
        QWEN_EMBED_URL,
        json={"model": QWEN_EMBED_MODEL, "input": text},
    )
    response.raise_for_status()
    payload = response.json()
    embedding = payload.get("embedding")

    if embedding is None:
        raise RuntimeError("Embedding response missing 'embedding' field")

    return embedding
