[mypy]
python_version = 3.13
explicit_package_bases = True
ignore_missing_imports = True
warn_return_any = True
warn_unused_configs = True

[mypy-requests.*]
ignore_missing_imports = True

[mypy-sentence_transformers.*]
ignore_missing_imports = True

[mypy-neo4j.*]
ignore_missing_imports = True

[mypy-pymilvus.*]
ignore_missing_imports = True
